# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogTeo', '0002_auto_20160810_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('cuerpoComentario', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='idEntrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBlogTeo.Entrada'),
        ),
    ]
