# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogTeo', '0005_auto_20160816_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='appBlogTeo.Etiqueta'),
        ),
    ]
